# Generated by Django 3.1.3 on 2020-12-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='photo',
        ),
    ]
